### ISSUE TITLE
Missing pagination support

### ISSUE THREAD

**Issue by p-louis** [linked-planet/kotlin-insight-wrapper#3]
## Observation
All functions used for getting a list of results will only ever return a maximum of 25 results, regardless of how many results the given filter matches.

## Expectation
The result-list returned by these functions returns all results matching the given filter.

## Technical notes
25 is the default page size of the Insight REST-API.
The query parameters for pagination are 
`resultsPerPage` and `page`

**Comment by betacore** [comment]
Fixed in aa6387e
To get the number of pages for a request:
- ObjectOperator.getObjectPages("Test")
- ObjectOperator.getObjectIqlPages("Test", "Name is not empty")
To get all objects cumulated:
- ObjectOperator.getObjects("Test")
- ObjectOperator.getObjectsByIQL("Test", "Name is not empty")
To get paginated:
- ObjectOperator.getObjects("Test", 2, 26)
- ObjectOperator.getObjectsByIQL("Test", "Name is not empty", 2, 26)
